name: Verify Build & Preview

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify app builds and runs preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: app

      - name: Run build
        run: npm run build
        working-directory: app

      - name: Run preview server test
        run: |
          npm run preview &
          PREVIEW_PID=$!
          sleep 5
          curl -f http://localhost:4173 || (echo "Preview server failed" && kill $PREVIEW_PID && exit 1)
          kill $PREVIEW_PID
        working-directory: app
